server:
  http:
    enabled: true
    host: "0.0.0.0"
    port: 7070
    static_path: "/web"
    static_dir: "./web"
  grpc:
    enabled: true
    host: "0.0.0.0"
    port: 7071

security:
  enable_whitelist: true
  pin_required: false
  pin: ""
  rate_limit_enabled: true
  rate_limit_per_min: 60
  allowed_commands: []

commands:
  config_path: "config/commands-v2.json"
  hot_reload: true

mqtt:
  enabled: false
  broker: "localhost"
  port: 1883
  username: ""
  password: ""
  client_id: "lazy-ctrl-agent"
  topic_base: "lazy-ctrl"

log:
  level: "info"
  format: "json"
  output_path: ""