basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  github_com_myczh-1_lazy-ctrl-agent_internal_service_executor.ExecutionResult:
    properties:
      error:
        type: string
      execution_time:
        $ref: '#/definitions/time.Duration'
      exit_code:
        type: integer
      output:
        type: string
      success:
        type: boolean
    type: object
  time.Duration:
    enum:
    - -9223372036854775808
    - 9223372036854775807
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    type: integer
    x-enum-varnames:
    - minDuration
    - maxDuration
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
host: localhost:7070
info:
  contact:
    email: support@lazy-ctrl.com
    name: API Support
    url: https://github.com/myczh-1/lazy-ctrl-agent
  description: Remote computer control agent with HTTP/gRPC/MQTT support
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Lazy-Ctrl Agent API
  version: 2.0.0
paths:
  /commands:
    get:
      consumes:
      - application/json
      description: Get a list of all registered commands
      parameters:
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                commands:
                  additionalProperties: true
                  type: object
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: List all commands
      tags:
      - commands
    post:
      consumes:
      - application/json
      description: Create a new command with the specified configuration
      parameters:
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      - description: Command configuration
        in: body
        name: command
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                id:
                  type: string
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: Create a new command
      tags:
      - commands
  /commands/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing command by its ID
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: string
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                message:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: Delete a command
      tags:
      - commands
    put:
      consumes:
      - application/json
      description: Update an existing command configuration
      parameters:
      - description: Command ID
        in: path
        name: id
        required: true
        type: string
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      - description: Updated command configuration
        in: body
        name: command
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: Update a command
      tags:
      - commands
  /execute:
    get:
      consumes:
      - application/json
      description: Execute a registered command by its ID with optional timeout
      parameters:
      - description: Command ID
        in: query
        name: id
        required: true
        type: string
      - description: 'Timeout in seconds (default: 30)'
        in: query
        name: timeout
        type: integer
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_myczh-1_lazy-ctrl-agent_internal_service_executor.ExecutionResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: Execute a command
      tags:
      - execute
  /health:
    get:
      consumes:
      - application/json
      description: Get the health status of the lazy-ctrl-agent service
      parameters:
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                status:
                  type: string
                timestamp:
                  type: integer
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: Health check
      tags:
      - system
  /reload:
    post:
      consumes:
      - application/json
      description: Reload commands from the configuration file
      parameters:
      - description: PIN for authentication (if required)
        in: header
        name: X-Pin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/gin.H'
            - properties:
                message:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - PinAuth: []
      summary: Reload commands configuration
      tags:
      - commands
securityDefinitions:
  PinAuth:
    description: PIN authentication for secure access
    in: header
    name: X-Pin
    type: apiKey
swagger: "2.0"
